//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoBPM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInputField : DemoBPM.Common.APISupport.SEObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbInputField()
        {
            this.tbInputFieldInstances = new HashSet<tbInputFieldInstance>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StepID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> InputFieldTypeID { get; set; }
        public string Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInputFieldInstance> tbInputFieldInstances { get; set; }
        public virtual tbInputFieldType tbInputFieldType { get; set; }
        public virtual tbRequest tbRequest { get; set; }
        public virtual tbStep tbStep { get; set; }
    }
}
