//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoBPM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStep : DemoBPM.Common.APISupport.SEObject
    {
        public int ID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ApproverRoleID { get; set; }
        public Nullable<int> StepIndex { get; set; }
    
        public virtual tbRequest tbRequest { get; set; }
        public virtual tbRole tbRole { get; set; }
    }
}
