//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoBPM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStepInstance : DemoBPM.Common.APISupport.SEObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbStepInstance()
        {
            this.tbInputFieldInstances = new HashSet<tbInputFieldInstance>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RequestInstanceID { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public string DefaultContent { get; set; }
        public string Status { get; set; }
        public Nullable<int> StepID { get; set; }
        public string ResponseMessage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbInputFieldInstance> tbInputFieldInstances { get; set; }
        public virtual tbRequestInstance tbRequestInstance { get; set; }
        public virtual tbStep tbStep { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
